# -*- coding: utf-8 -*-
"""modelisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmOvL9wpcdHdsG5GkA8URNEudNL6skR-

# TP1 - Prédiction de la Réussite Étudiante

## 1. Identifier les étudiants qui ont besoin d’un plan d’aide à la réussite. Est-ce que l’on est dans un cas de classification? Expliquer.

<div class="alert alert-success">
  <strong><i class="fa fa-chevron-circle-right"></i> Réponse :</strong>
  Oui, il s'agit d'un problème de <strong>classification binaire</strong>.
  <br>L'objectif est de prédire une variable qualitative discrète à deux modalités :
  <code>Réussite</code> (étudiant ne nécessitant pas de plan d'aide) ou <code>Échec/À risque</code> (étudiant nécessitant un plan d'aide).
  Les algorithmes d'apprentissage apprendront à associer les caractéristiques des étudiants (âge, temps d'étude, soutien familial, etc.) à cette étiquette binaire pour classer les nouveaux étudiants dans l'une ou l'autre catégorie.
</div>

## 2. Importation des bibliotheques

<div class="alert alert-info">
  <strong><i class="fa fa-chevron-circle-down"></i> Note:</strong> importation des bibliotheques.
</div>
"""

# ## 2. Importation des bibliotheques

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             roc_auc_score, confusion_matrix, classification_report,
                             roc_curve, auc, balanced_accuracy_score)
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectFromModel
import xgboost as xgb
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import warnings
import joblib

warnings.filterwarnings('ignore')

# Options d'affichage
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: f'{x:.2f}')

#!pip install pyfiglet
#!pip install xgboost

# ## 3. Chargement des données
print("="*40)
print("CHARGEMENT DES DONNÉES")
print("="*40)
print("\n")
df = pd.read_csv('data/data_etudiants.csv', sep=',', encoding='utf-8', low_memory=False)

print(f"Dimension du dataset : {df.shape}\n")
print(f"Colonnes : {df.columns.tolist()}\n")

print(f"Dimension du dataset : {df.shape}")

# Visualisation des données
print("\n APERCU DES DONNEES\n")
print("Affichage des 5 premières lignes du dataset\n")
print(df.head()) # Affiche les 5 premières lignes du dataset
print("="*150)
print("\n")
print("Affichage de 3 dernieres lignes du dataset\n")
print(df.tail(3)) # Affiche les 3 dernières lignes
print("="*150)
print("\n")
print("Affichage de 3 lignes aleatoires\n")
print(df.sample(3)) # Affiche 3 lignes aléatoires

"""## 4. Analyse Exploratoire des Données

<div class="alert alert-info">
  <strong><i class="fa fa-chevron-circle-down"></i> Note:</strong> calcul des statistiques descriptives.
</div>
"""

#!pip install sweetviz
#!pip install fg-data-profiling

import os
import webbrowser
import sweetviz as sv
from ydata_profiling import ProfileReport
import data_profiling

os.makedirs("reports", exist_ok=True)

# YDATA PROFILING
profile = ProfileReport(
    df,
    title="Rapport EDA"
)

profile.to_file(
    "reports/rapport_profiling.html"
)


# SWEETVIZ
report = sv.analyze(df)

report.show_html(
    "reports/rapport_sweetviz.html"
)

# Statistiques de base pour les colonnes numériques
desc = df.describe()
print(desc)

stats = []

for col in df.select_dtypes(include=['int64', 'float64']).columns:

    mean = df[col].mean()
    std = df[col].std()
    min_val = df[col].min()
    max_val = df[col].max()

    # interprétation
    if std > mean:
        interpretation = "Forte dispersion"
    else:
        interpretation = "Données stables"

    stats.append({
        "Variable": col,
        "Moyenne": round(mean, 2),
        "Ecart_type": round(std, 2),
        "Min": min_val,
        "Max": max_val,
        "Interpretation": interpretation
    })

# création du dataframe final
df_stats = pd.DataFrame(stats)

# affichage
df_stats

# Statistiques pour les colonnes catégorielles
df.describe(include=['object'])

cat_stats = []

for col in df.select_dtypes(include=['object']).columns:

    # nombre de modalités
    n_unique = df[col].nunique()

    # modalité la plus fréquente
    top_value = df[col].mode()[0]
    top_freq = df[col].value_counts().iloc[0]

    # pourcentage de la modalité dominante
    top_freq_pct = (top_freq / len(df)) * 100

    cat_stats.append({
        "Variable": col,
        "Nb_modalités": n_unique,
        "Modalité_dominante": top_value,
        "Fréquence": top_freq,
        "Fréquence_%": round(top_freq_pct, 2)
    })

df_cat_stats = pd.DataFrame(cat_stats)

df_cat_stats

missing_values = df.isnull().sum()

missing = missing_values[missing_values > 0]

if len(missing) == 0:
    print("Aucune valeur manquante.")
else:
    print("\nValeurs manquantes :")
    print(missing)

    missing_percentage = (missing / len(df)) * 100

    print("\nPourcentage de valeurs manquantes :")
    print(missing_percentage.round(2).astype(str) + "%")

# ## 4. Analyse approfondie des données

# Création de la variable cible
df['success'] = (df['passed'] == 'yes').astype(int)

# Analyse du déséquilibre des classes
print("\n" + "="*35)
print("ANALYSE DU DÉSÉQUILIBRE DES CLASSES")
print("="*35)
class_counts = df['success'].value_counts()
print(f"Réussite (1): {class_counts[1]} ({class_counts[1]/len(df)*100:.2f}%)")
print(f"Échec (0): {class_counts[0]} ({class_counts[0]/len(df)*100:.2f}%)")


## Autres statistiques intéressantes
print("\n--- Répartition par temps d'étude ---")
print(df['studytime'].value_counts().sort_index())
print("\n--- Moyenne de l'âge par statut de réussite ---")
print(df.groupby('success')['age'].mean())


# Seuil pour déséquilibre significatif
if class_counts[0] / class_counts[1] < 0.5 or class_counts[1] / class_counts[0] < 0.5:
    print(" Dataset déséquilibré - Nécessite des techniques de rééchantillonnage")
    use_balancing = True
else:
    use_balancing = False
    print(" Dataset équilibré")

# Feature Engineering - Création de nouvelles variables pertinentes
print("\n" + "="*35)
print("FEATURE ENGINEERING")
print("="*35)

# Indicateur de risque académique
df['academic_risk'] = ((df['failures'] > 0) & (df['studytime'] <= 2)).astype(int)

# Score de soutien familial
df['family_support_score'] = (
    (df['famsup'] == 'yes').astype(int) +
    (df['paid'] == 'yes').astype(int) +
    (df['activities'] == 'yes').astype(int)
)

# Score de consommation (alcool)
df['alcohol_score'] = (df['Dalc'] + df['Walc']) / 2

# Interaction âge × échecs passés
df['age_failures'] = df['age'] * df['failures']

# Absences normalisées (cap à 30 pour éviter l'effet des outliers)
df['absences_capped'] = np.where(df['absences'] > 30, 30, df['absences'])

print("Nouvelles features créées :")
print(" - academic_risk (risque académique)")
print(" - family_support_score (score de soutien familial)")
print(" - alcohol_score (score de consommation d'alcool)")
print(" - age_failures (interaction âge × échecs)")
print(" - absences_capped (absences plafonnées)")

"""<div class="alert alert-info">
  <strong><i class="fa fa-chevron-circle-down"></i> Visualisations rapides :</strong>
</div>
"""

# Création des graphiques
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# Distribution de la variable cible
sns.countplot(x='success', data=df, ax=axes[0])
axes[0].set_title('Distribution Réussite / Échec')
axes[0].set_xticklabels(['Échec', 'Réussite'])

# Relation Temps d'étude vs Réussite
sns.boxplot(x='success', y='studytime', data=df, ax=axes[1])
axes[1].set_title('Temps d\'étude vs Réussite')
axes[1].set_xticklabels(['Échec', 'Réussite'])

# Relation Nombre d'échecs passés vs Réussite
sns.boxplot(x='success', y='failures', data=df, ax=axes[2])
axes[2].set_title('Échecs passés vs Réussite')
axes[2].set_xticklabels(['Échec', 'Réussite'])

plt.tight_layout()
plt.show()

"""## 5. Préparation des données

<div class="alert alert-info">
<strong><i class="fa fa-chevron-circle-down"></i> Note:</strong> a. Identification des features/prédicteurs et de la colonne cible.
</div>
"""

# visualiser les corrélations entre les variables numériques
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
plt.figure(figsize=(12, 10))
correlation_matrix = df[numeric_cols].corr()

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matrice de corrélation')
plt.show()

print("\nMatrice de corrélation :")
corr_matrix = df[numeric_cols].corr()
print(corr_matrix.round(2))

print("\n")

# affichage des correlations fortes
threshold = 0.6
strong_pairs = []

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        corr_value = corr_matrix.iloc[i, j]
        if abs(corr_value) > threshold:
            strong_pairs.append([
                corr_matrix.columns[i],
                corr_matrix.columns[j],
                round(corr_value, 2)
            ])

strong_corr_df = pd.DataFrame(strong_pairs, columns=["Variable 1", "Variable 2", "Corrélation"])

print(strong_corr_df)

# ## 5. Préparation des données

print("\n" + "="*30)
print("PRÉPARATION DES DONNÉES")
print("="*30)

# Séparation des features et de la cible
target_col = 'success'
feature_cols = [col for col in df.columns if col not in ['passed', target_col]]

X = df[feature_cols]
y = df[target_col]

# Identification des types de colonnes
num_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()

print(f"Variables numériques : {len(num_cols)}")
print(f"Variables catégorielles : {len(cat_cols)}")

# Handle potential NaNs in categorical columns
for col in cat_cols:
    X[col] = X[col].fillna('')

# Split avec stratification pour maintenir la distribution des classes
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nTaille train set: {X_train.shape}")
print(f"Taille test set: {X_test.shape}")

# Pipelines de prétraitement
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, num_cols),
        ('cat', categorical_transformer, cat_cols)
    ]
)

## 6. Modèles avec sélection de features et SMOTE (obligatoire car classes déséquilibrées)
# Définition des modèles

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'XGBoost': xgb.XGBClassifier(n_estimators=100, learning_rate=0.1,
                random_state=42, eval_metric='logloss', use_label_encoder=False),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42)
    }

# Paramètres pour la sélection de features
FEATURE_SELECTION_THRESHOLD = 'median'

print("\n" + "="*60)
print("ENTRAÎNEMENT DES MODÈLES AVEC SÉLECTION DE FEATURES ET SMOTE")
print("="*60)
print(f"Seuil de sélection des features: {FEATURE_SELECTION_THRESHOLD}")
print(f"SMOTE activé pour tous les modèles (déséquilibre détecté)\n")

# Stockage des résultats
results = {}
trained_models = {}
feature_counts = {}

for name, model in models.items():
    print(f"\n--- {name} ---")

    # Pipeline UNIQUE : prétraitement → sélection features → SMOTE → classifieur
    pipeline = ImbPipeline(steps=[
        ('preprocessor', preprocessor),
        ('feature_selection', SelectFromModel(model, threshold=FEATURE_SELECTION_THRESHOLD)),
        ('smote', SMOTE(random_state=42)),
        ('classifier', model)
    ])

    print(" SMOTE activé (gestion du déséquilibre)")

    # Pas besoin de class_weight ou scale_pos_weight car SMOTE s'en occupe déjà !

    # Entraînement du pipeline
    pipeline.fit(X_train, y_train)
    trained_models[name] = pipeline

    # Récupération du nombre de features après sélection
    if hasattr(pipeline.named_steps['feature_selection'], 'get_support'):
        n_features_before = X_train.shape[1]
        n_features_after = pipeline.named_steps['preprocessor'].transform(X_train).shape[1]
        n_features_selected = pipeline.named_steps['feature_selection'].get_support().sum()
        feature_counts[name] = {
            'original': n_features_before,
            'after_encoding': n_features_after,
            'selected': n_features_selected
        }
        print(f"  Features: {n_features_before} → {n_features_after} encodées → {n_features_selected} sélectionnées")

    # Prédictions
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1] if hasattr(pipeline, 'predict_proba') else None

    # Métriques
    results[name] = {
        'Accuracy': accuracy_score(y_test, y_pred),
        'Balanced Accuracy': balanced_accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, zero_division=0),
        'Recall': recall_score(y_test, y_pred, zero_division=0),
        'F1-Score': f1_score(y_test, y_pred, zero_division=0),
        'AUC-ROC': roc_auc_score(y_test, y_pred_proba) if y_pred_proba is not None else None
    }

# ## 7. Affichage des résultats

print("\n" + "="*35)
print("RÉSULTATS COMPARATIFS DES MODÈLES")
print("="*35)

results_df = pd.DataFrame(results).T
results_df = results_df.round(4)
print(results_df.to_string())

# ## 8. Sélection du meilleur modèle
print("\n" + "="*35)
print("SÉLECTION DU MEILLEUR MODÈLE")
print("="*35)

# Tri selon le F1-Score
best_model_name = results_df['F1-Score'].idxmax()
best_model = trained_models[best_model_name]
best_score = results_df.loc[best_model_name, 'F1-Score']

print(f"\n Meilleur modèle : {best_model_name}")
print(f" F1-Score : {best_score:.4f}")

# Affichage des performances détaillées
print(f"\n=== Performances détaillées ===")
for metric, value in results[best_model_name].items():
    print(f"{metric:20s} : {value:.4f}")

# ## 9. Analyse approfondie du meilleur modèle

print("\n" + "="*45)
print(f"ANALYSE APPROFONDIE-{best_model_name}")
print("="*45)

# Rapport de classification
y_pred_best = best_model.predict(X_test)
print("\n=== Rapport de classification ===")
print(classification_report(y_test, y_pred_best, target_names=['Échec', 'Réussite']))

# Matrice de confusion
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Échec', 'Réussite'],
            yticklabels=['Échec', 'Réussite'])
plt.title(f'Matrice de confusion - {best_model_name}', fontsize=14, fontweight='bold')
plt.xlabel('Prédiction', fontsize=12)
plt.ylabel('Valeur réelle', fontsize=12)
plt.tight_layout()
plt.show()

# ## 10. Importance des variables

print("\n=== Analyse des features sélectionnées ===")

# Récupération des feature names après preprocessing
feature_names_encoded = best_model.named_steps['preprocessor'].get_feature_names_out()

# Récupération du sélecteur de features
selector = best_model.named_steps['feature_selection']
selected_mask = selector.get_support()
selected_features = feature_names_encoded[selected_mask]
dropped_features = feature_names_encoded[~selected_mask]

print(f"\n Features conservées: {len(selected_features)}/{len(feature_names_encoded)}")
print(f" Features éliminées: {len(dropped_features)}/{len(feature_names_encoded)}")

# Importance des features pour le classifieur
classifier = best_model.named_steps['classifier']

if hasattr(classifier, 'feature_importances_'):
    print("\n=== Top 15 features les plus importantes ===")

    # Récupération des importances uniquement pour les features sélectionnées
    importances = classifier.feature_importances_

    importance_df = pd.DataFrame({
        'Variable': selected_features,
        'Importance': importances
    }).sort_values('Importance', ascending=False)

    print(importance_df.head(15).to_string(index=False))

    # Visualisation
    plt.figure(figsize=(12, 8))
    top_features = importance_df.head(15)
    sns.barplot(data=top_features, x='Importance', y='Variable', palette='viridis')
    plt.title(f'Top 15 variables importantes - {best_model_name}', fontsize=14, fontweight='bold')
    plt.xlabel('Importance', fontsize=12)
    plt.ylabel('Variables', fontsize=12)
    plt.tight_layout()
    plt.show()

elif hasattr(classifier, 'coef_'):
    print("\n=== Top 15 coefficients (importance) ===")
    coefs = classifier.coef_[0]
    importance_df = pd.DataFrame({
        'Variable': selected_features,
        'Coefficient': coefs
    })
    importance_df['Importance'] = np.abs(importance_df['Coefficient'])
    importance_df = importance_df.sort_values('Importance', ascending=False)

    print(importance_df.head(15).to_string(index=False))

    # Visualisation
    plt.figure(figsize=(12, 8))
    top_features = importance_df.head(15)
    colors = ['red' if x < 0 else 'green' for x in top_features['Coefficient']]
    sns.barplot(data=top_features, x='Coefficient', y='Variable', palette=colors)
    plt.title(f'Top 15 coefficients - {best_model_name}', fontsize=14, fontweight='bold')
    plt.xlabel('Coefficient', fontsize=12)
    plt.ylabel('Variables', fontsize=12)
    plt.axvline(x=0, color='black', linestyle='-', linewidth=0.5)
    plt.tight_layout()
    plt.show()

# ## 11. Visualisation de l'impact de la sélection de features

print("\n" + "="*40)
print("IMPACT DE LA SÉLECTION DE FEATURES")
print("="*40)

# Comparaison du nombre de features
comparison_df = pd.DataFrame(feature_counts).T
comparison_df['reduction_ratio'] = (1 - comparison_df['selected'] / comparison_df['after_encoding']) * 100
print("\nTaux de réduction des features par modèle:")
print(comparison_df.to_string())

# Visualisation
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Graphique 1: Nombre de features
ax1 = axes[0]
models_names = list(feature_counts.keys())
original_counts = [feature_counts[m]['original'] for m in models_names]
encoded_counts = [feature_counts[m]['after_encoding'] for m in models_names]
selected_counts = [feature_counts[m]['selected'] for m in models_names]

x = np.arange(len(models_names))
width = 0.25

ax1.bar(x - width, original_counts, width, label='Originales', alpha=0.8)
ax1.bar(x, encoded_counts, width, label='Après encodage', alpha=0.8)
ax1.bar(x + width, selected_counts, width, label='Sélectionnées', alpha=0.8)
ax1.set_xlabel('Modèles', fontsize=12)
ax1.set_ylabel('Nombre de features', fontsize=12)
ax1.set_title('Comparaison du nombre de features', fontsize=14, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels(models_names, rotation=45, ha='right')
ax1.legend()
ax1.grid(True, alpha=0.3)

# Graphique 2: Performance vs réduction
ax2 = axes[1]
reduction_ratios = [comparison_df.loc[m, 'reduction_ratio'] for m in models_names]
f1_scores = [results[m]['F1-Score'] for m in models_names]

scatter = ax2.scatter(reduction_ratios, f1_scores, s=100, c=range(len(models_names)), cmap='viridis')
ax2.set_xlabel('Taux de réduction des features (%)', fontsize=12)
ax2.set_ylabel('F1-Score', fontsize=12)
ax2.set_title('Performance vs Réduction des features', fontsize=14, fontweight='bold')
ax2.grid(True, alpha=0.3)

# Annotation des points
for i, name in enumerate(models_names):
    ax2.annotate(name, (reduction_ratios[i], f1_scores[i]),
                xytext=(5, 5), textcoords='offset points', fontsize=9)

plt.colorbar(scatter, ax=ax2, label='Modèles')
plt.tight_layout()
plt.show()

import pickle
import os

print("\n" + "="*80)
print("SAUVEGARDE DU MEILLEUR MODÈLE")
print("="*80)

# --- Affichage des informations du meilleur modèle ---
best_metrics = results[best_model_name]

accuracy = best_metrics.get('Accuracy', best_metrics.get('cv_score', None))
precision = best_metrics.get('Precision', None)
recall = best_metrics.get('Recall', None)
f1_score = best_metrics.get('F1-Score', None)

print(f"Accuracy      : {accuracy:.2f}")
print(f"Precision     : {precision:.2f}")
print(f"Recall        : {recall:.2f}")
print(f"F1-score      : {f1_score:.2f}")

if 'selected_features' in globals():
    print(f"Nombre de features sélectionnées : {len(selected_features)}")

# --- Justification du choix du modèle ---
print("\nJUSTIFICATION DU CHOIX DU MODÈLE")
print("-" * 50)

print(
    f"Le modèle '{best_model_name}' a été sélectionné car il obtient "
    f"les meilleures performances globales (notamment F1-score et recall), "
    f"ce qui est essentiel dans un contexte de déséquilibre de classes."
)

if use_balancing:
    print("De plus, la gestion du déséquilibre (SMOTE ou class_weight) a amélioré sa robustesse.")

if FEATURE_SELECTION_THRESHOLD:
    print("La sélection de variables a permis de réduire la dimension et d'améliorer la généralisation.")

# --- Sauvegarde du modèle + métadonnées ---
model_info = {
    'model': best_model,
    'model_name': best_model_name,
    'performance': results[best_model_name],
    'feature_selection_threshold': FEATURE_SELECTION_THRESHOLD,
    'use_balancing': use_balancing,
    'feature_counts': feature_counts[best_model_name],
    'selected_features': selected_features.tolist() if 'selected_features' in globals() else None
}

# Créer le répertoire 'models' s'il n'existe pas
os.makedirs('models', exist_ok=True)

# Sauvegarde
with open("models/meilleur_modele_avec_selection.pkl", "wb") as file:
    pickle.dump(model_info, file)

print("\nModèle sauvegardé sous : models/meilleur_modele_avec_selection.pkl")

# ## 15. Résumé final

print("\n" + "="*80)
print("RÉSUMÉ FINAL")
print("="*80)

print(f"""
📊 RÉSULTATS DE L'ANALYSE:

1. Dataset: {df.shape[0]} étudiants, {df.shape[1]} variables
2. Déséquilibre des classes: {'Oui' if use_balancing else 'Non'}
3. Feature engineering: 5 nouvelles variables créées
4. Sélection de features: Oui (seuil = {FEATURE_SELECTION_THRESHOLD})
5. Meilleur modèle: {best_model_name}
6. F1-Score: {results[best_model_name]['F1-Score']:.4f}
7. Features originales: {feature_counts[best_model_name]['original']}
8. Features après encodage: {feature_counts[best_model_name]['after_encoding']}
9. Features sélectionnées: {feature_counts[best_model_name]['selected']}
10. Taux de réduction: {comparison_df.loc[best_model_name, 'reduction_ratio']:.1f}%

📈 MÉTRIQUES CLÉS:
   - Accuracy: {results[best_model_name]['Accuracy']:.4f}
   - Balanced Accuracy: {results[best_model_name]['Balanced Accuracy']:.4f}
   - Precision: {results[best_model_name]['Precision']:.4f}
   - Recall: {results[best_model_name]['Recall']:.4f}
   - F1-Score: {results[best_model_name]['F1-Score']:.4f}
   - AUC-ROC: {results[best_model_name]['AUC-ROC']:.4f}

✅ Modèle prêt pour la prédiction de la réussite étudiante!
""")

